/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:03f62368-3bf5-448e-9e16-ce679560b9fa",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_Mqf4ADIlv",
    "aws_user_pools_web_client_id": "uagf0in3hnn6unvuqrvtmk1n5",
    "oauth": {}
};


export default awsmobile;
