/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:764417993088",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_cW50UrU6B",
    "aws_user_pools_web_client_id": "gharse486bcbcd_app_clientWeb",
    "oauth": {}
};


export default awsmobile;
